### ISSUE TITLE
Into and From traits in natives.rs

### ISSUE THREAD

**Issue by S-Erik** [JErnestoMtz/rapl#2]
In the file [src/natives.rs](https://github.com/JErnestoMtz/rapl/blob/main/src/natives.rs) the [Into trait](https://doc.rust-lang.org/std/convert/trait.Into.html) is implemented for [arrays](https://doc.rust-lang.org/std/primitive.array.html), [Vec](https://doc.rust-lang.org/std/vec/struct.Vec.html), [Range](https://doc.rust-lang.org/std/ops/struct.Range.html) and [string slices](https://doc.rust-lang.org/std/primitive.str.html).

[Clippy](https://doc.rust-lang.org/stable/clippy/) suggests that one should always prefer to implement the [From trait](https://doc.rust-lang.org/std/convert/trait.From.html)
> because implementing From automatically provides one with an implementation of [Into](https://doc.rust-lang.org/std/convert/trait.Into.html) thanks to the blanket implementation in the standard library.

This is also discussed in [this Issue](https://github.com/rust-lang/rust-clippy/issues/6456) in the Clippy Github.

Therefore, I suggest implementing the Into trait instead of the From trait in natives.rs.

A pull request implementing the From trait instead of the Into trait can be found here: #3

**Comment by JErnestoMtz** [comment]
Thanks a lot!! I wasn't aware that From was preferred, its good to know.
